---
- name: Install docker-compose
  tags:
    - install
  # when: docker_compose_version | length == 0
  when: docker_compose_action == "install"
  block:
    - name: Get information on the latest docker-compose release from github
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ docker_compose_github_repo }}/releases/latest"
        method: GET
      register: _docker_compose_github_release
      check_mode: false
      until: _docker_compose_github_release.status == 200
      retries: 5
      delay: 15

    - name: Extract the name of the latest docker-compose release tag
      ansible.builtin.set_fact:
        docker_compose_version: "{{ _docker_compose_github_release['json'] | json_query('tag_name') }}"

    - name: Download docker-compose
      become: true
      ansible.builtin.get_url:
        url: "https://github.com/{{ docker_compose_github_repo }}/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}" # noqa 204
        dest: "{{ docker_compose_executable }}"
        mode: "0755"


- name: Uninstall docker-compose
  become: true
  tags:
    - uninstall
  when: docker_compose_action == "uninstall"
  ansible.builtin.file:
    path: "{{ docker_compose_executable }}"
    state: absent
  # ignore_errors: true
